#!/bin/bash

dir=`dirname "$0"`

if [ ! -z "$DUMMY_LIB_GEN" ]; then
	if [ ! -z "$KLLVM" ]; then
            ${KLLVM}/build/bin/clang "$@"
        elif [ -f /home/acanino/llvm/build/bin/clang ]; then
	    /home/acanino/llvm/build/bin/clang "$@"
        elif [ -f /home/aspire/llvm/build/bin/clang ]; then
	    /home/aspire/llvm/build/bin/clang "$@"
	else
	    echo "Compiler not found"
	    exit 1
	fi
else
	$dir/gcc-orig "$@"
fi
exit
