#!/bin/bash

export LZLOAD_LIB="libxcb-shape.so.0:libxcb-res.so.0:libxcb-sync.so.1:libxcb-glx.so.0:libxcb-xinerama.so.0:libxcb-xfixes.so.0:libxcb-xf86dri.so.0:libxcb-xvmc.so.0:libxcb.so.1:libxcb-composite.so.0:libxcb-dri2.so.0:libxcb-damage.so.0:libxcb-dri3.so.0:libxcb-randr.so.0:libxcb-dpms.so.0:libxcb-screensaver.so.0:libxcb-record.so.0:libxcb-present.so.0:libxcb-shm.so.0:libxcb-render.so.0:libxcb-xtest.so.0:libxcb-xv.so.0:libxcb-xinput.so.0:libxcb-xkb.so.1:libcrypto.so.1.1:libssl.so.1.1:libsepol.so.1:libpng16.so.16:libcurl.so.4:libuuid.so.1:libsmartcols.so.1:libmount.so.1:libfdisk.so.1:libblkid.so.1:libscram.so.2:libsql.so.2:libgs2.so.2:libgssapiv2.so.2:libntlm.so.2:libsasldb.so.2:libplain.so.2:liblogin.so.2:libanonymous.so.2:libcrammd5.so.2:libldapdb.so.2:libotp.so.2:libdigestmd5.so.2:libsasl2.so.2:libudev.so.1:libsystemd.so.0:libnss_myhostname.so.2:libnss_resolve.so.2:libnss_mymachines.so.2:libnss_systemd.so.2:libacl.so.1:libcupsimage.so.2:libcups.so.2:liblber-2.4.so.2:libldap-2.4.so.2:libldap_r-2.4.so.2:libslapi-2.4.so.2:libavahi-core.so.7:libavahi-gobject.so.0:libavahi-client.so.3:libavahi-common.so.3:libavahi-glib.so.1:libnghttp2.so.14:libcupsfilters.so.1:libfontembed.so.1:libjbig.so.0:libgpg-error.so.0:libnettle.so.6:libhogweed.so.4:libpixman-1.so.0:libXdmcp.so.6:libjpeg.so.62:libturbojpeg.so.0:libgmp.so.10:libapt-pkg.so.5.0:libapt-private.so.0.0:libapt-inst.so.2.0:libfreetype.so.6:libseccomp.so.2:liblzma.so.5:libsemanage.so.1:libpoppler-glib.so.8:libpoppler-qt5.so.1:libpoppler-cpp.so.0:libpoppler.so.82:libX11.so.6:libX11-xcb.so.1:libXau.so.6:libfontconfig.so.1:libXft.so.2:libICE.so.6:libpam.so.0:libpamc.so.0:libpam_misc.so.0:libkdb_ldap.so.1:libdb.so.1:libkrb5support.so.0:libprofile.so.1:libkdb5.so.9:libk5crypto.so.3:libkrb5.so.3:libgssapi_krb5.so.2:libgssrpc.so.4:libkadm5clnt_mit.so.11:libkadm5srv_mit.so.11:libkrad.so.0:libz.so.1:libssh2.so.1:libwebpdemux.so.2:libwebpmux.so.3:libwebp.so.6:libdbus-1.so.3:libSM.so.6:libbz2.so.1.0:liblz4.so.1:libpcre32.so.3:libpcre16.so.3:libpcre.so.3:libpcreposix.so.3:libpcrecpp.so.0:libattr.so.1:libbsd.so.0:librtmp.so.1:libsqlite3.so.0:libpaper.so.1:libcom_err.so.2:libss.so.2:libe2p.so.2:libext2fs.so.2:libfontenc.so.1:libXmuu.so.1:libXmu.so.6:libexpat.so.1:libexpatw.so.1:liblcms2.so.2:libXt.so.6:libcap-ng.so.0:libffi.so.6:libopenjp2.so.7:libopenjpip.so.7:libopenjp3d.so.7:libtiffxx.so.5:libtiff.so.5:libidn2.so.0:libXrender.so.1:libtasn1.so.6:libunistring.so.2:libp11-kit.so.0:libpsl.so.5:libgcrypt.so.20:libXext.so.6:libgnutls-openssl.so.27:libgnutls-dane.so.0:libgnutlsxx.so.28:libgnutls.so.30:libcairo.so.2:libcairo-gobject.so.2:libcairo-script-interpreter.so.2:"

# Path points to the real libraries
export LZ_LIBRARY_PATH=~/src-out/mod-lib:~/src-out/mod-lib/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/

# Path points to our lzload and fake libraries
export LD_LIBRARY_PATH=~/src-out/lib:$LD_LIBRARY_PATH

xpdf


